import { Head, Link } from '@inertiajs/react';
import { z } from 'zod';

import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { useInertiaAppForm } from '@/components/ui/form/use-inertia-app-form';
import { Heading } from '@/components/ui/heading';
import TwoFactorLayout from '@/layouts/two-factor-layout';
import { setup } from '@/routes/settings/two-factor';
import { store } from '@/routes/settings/two-factor/confirm';

const twoFactorConfirmSchema = z.object({
  code: z.string().min(6, 'code must be 6 digits').max(6, 'code must be 6 digits'),
});

export default function TwoFactorConfirm() {
  const { form, getServerError } = useInertiaAppForm({
    defaultValues: {
      code: '',
    },
    action: store().url,
    method: 'post',
    validators: {
      onSubmit: twoFactorConfirmSchema,
    },
  });

  return (
    <TwoFactorLayout>
      <Head title="Verify 2FA" />
      <form.AppForm>
        <Card.Root>
          <form.FormRoot>
            <Card.Header>
              <Heading level={2} title="Verify 2FA" />
            </Card.Header>
            <Card.Content className="flex flex-col gap-4">
              <p>
                enter the verification code generated by your authenticator app to complete the
                setup process.
              </p>
              <form.AppField name="code">
                {(field) => (
                  <field.Field label="verification code" serverError={getServerError('code')}>
                    <field.TextInput
                      autoFocus
                      type="text"
                      inputMode="numeric"
                      autoComplete="one-time-code"
                      maxLength={6}
                    />
                  </field.Field>
                )}
              </form.AppField>
            </Card.Content>
            <Card.Footer className="justify-between gap-2">
              <Button type="button" variant="secondary" render={<Link href={setup().url} />}>
                previous
              </Button>
              <form.SubmitButton submittingText="verifying...">verify</form.SubmitButton>
            </Card.Footer>
          </form.FormRoot>
        </Card.Root>
      </form.AppForm>
    </TwoFactorLayout>
  );
}
